version: 2
jobs: 
  build:
    docker:
      - images circleci/node:7.10
    steps: 
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - run: 
          name: Run tests
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test